version: "3.9"

services:
  tunnel:
    build: .
    image: ghcr.io/your-org/simple-tunnel:latest
    container_name: simple-tunnel
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DOMAIN_BASE=${DOMAIN_BASE}
    # ports:
    # - "3000:3000"
    # - "3001:3001" # optional metrics/admin
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3000/health"]
      interval: 30s
      timeout: 3s
      retries: 3
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.tunnel-svc.loadbalancer.server.port=3000"
      - "traefik.http.routers.tunnel-public.rule=HostRegexp(`{subdomain:[a-z0-9-]+}.${DOMAIN_BASE}`)"
      - "traefik.http.routers.tunnel-public.entrypoints=websecure"
      - "traefik.http.routers.tunnel-public.tls=true"
      - "traefik.http.routers.tunnel-public.tls.certresolver=${TRAEFIK_CERTRESOLVER:-letsencrypt}"
      - "traefik.http.routers.tunnel-public.service=tunnel-svc"
      - "traefik.http.routers.tunnel-public.middlewares=tunnel-chain@docker"
      - "traefik.http.routers.tunnel-connect.rule=Host(`${DOMAIN_BASE}`) && Path(`/connect`)"
      - "traefik.http.routers.tunnel-connect.entrypoints=websecure"
      - "traefik.http.routers.tunnel-connect.tls=true"
      - "traefik.http.routers.tunnel-connect.tls.certresolver=${TRAEFIK_CERTRESOLVER:-letsencrypt}"
      - "traefik.http.routers.tunnel-connect.service=tunnel-svc"
      - "traefik.http.routers.tunnel-connect.middlewares=tunnel-chain@docker"
      - "traefik.http.middlewares.tunnel-headers.headers.browserXssFilter=true"
      - "traefik.http.middlewares.tunnel-headers.headers.contentTypeNosniff=true"
      - "traefik.http.middlewares.tunnel-headers.headers.frameDeny=true"
      - "traefik.http.middlewares.tunnel-headers.headers.stsSeconds=31536000"
      - "traefik.http.middlewares.tunnel-headers.headers.stsIncludeSubdomains=true"
      - "traefik.http.middlewares.tunnel-headers.headers.stsPreload=true"
      - "traefik.http.middlewares.tunnel-compress.compress=true"
      - "traefik.http.middlewares.tunnel-rate.ratelimit.average=50"
      - "traefik.http.middlewares.tunnel-rate.ratelimit.burst=100"
      - "traefik.http.middlewares.tunnel-rate.ratelimit.period=1s"
      - "traefik.http.middlewares.tunnel-chain.chain.middlewares=tunnel-headers,tunnel-compress,tunnel-rate"
