version: "3.9"

services:
  tunnel:
    build: .
    image: ghcr.io/your-org/simple-tunnel:latest
    container_name: simple-tunnel
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DOMAIN_BASE=${DOMAIN_BASE}
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://127.0.0.1:3000/health"]
      interval: 30s
      timeout: 3s
      retries: 3
    labels:
      - "traefik.http.routers.preview-simpletunnel.rule=HostRegexp(`{subdomain:[a-z0-9-]+}.${DOMAIN_BASE}`)"
